### PR TITLE
feat: Event search and event pages

### PR DESCRIPTION
**Pull request by quinchs**
## Summary
This PR adds the event search functionality as well as individual event pages.

### TODO
- [x] Markdown styling (figma team needed!)
- [x] Consistent scrollbar styles
- [x] Fix bug with expanded summary on page load
- [x] Code cleanup
- [ ] Implement design feedback
    - [ ] Better tooltip for contributors

### CODE REVIEW

**Review by MeguminSama — APPROVED** [review]
NICE

**Review by Liege72 — CHANGES_REQUESTED** [review]
- Remove carrot next to headers (make it so ppl can click on the title for full dropdown)
- Increase line height in descriptions on sidebar items
- Decrease font-weight on all Whitney 16px (use the description below main image as an example)
- Remove margins on the top and bottom that overlap
- Create margin below searchbar so items do not go right into it
- Make padding to the left of headings and description in dropdowns only 1rem (instead of 2)
- Increase padding above headers by .5

**Review by goverfl0w — APPROVED** [review]

**Comment by quinchs** [comment]
@MeguminSama Can you find us a tooltip component that's not as scuffed as the one I'm using lmao

**Comment by quinchs** [comment]
I think the tooltip can be looked at in the future, for now this PR is complete

**Pull request merged**
